---

- name: Create sigstore network
  containers.podman.podman_network:
    name: "{{ sigstore_podman_network }}"

- name: Create Manifests/Configs Directory
  ansible.builtin.file:
    state: directory
    dest: "{{ item }}"
  loop:
    - "{{ kube_manifest_dir }}"
    - "{{ kube_configmap_dir }}"

- name: podman login to registry.redhat.io
  ansible.builtin.command: podman login registry.redhat.io -u '{{ registry_username }}' --password {{ registry_password }}

- name: Configure/Deploy nginx
  ansible.builtin.include_tasks: podman/nginx.yml

- name: Configure/Deploy Trillian
  ansible.builtin.include_tasks: podman/trillian.yml
  when: trillian_enabled | bool

- name: Setup Trillian Tree ID
  ansible.builtin.include_tasks: podman/createtree.yml
  when: trillian_enabled | bool

- name: Configure/Deploy Rekor
  ansible.builtin.include_tasks: podman/rekor.yml
  when: rekor_enabled | bool

- name: Configure/Deploy Fulcio
  ansible.builtin.include_tasks: podman/fulcio.yml
  when: fulcio_enabled | bool

- name: Configure/Deploy ctlog
  ansible.builtin.include_tasks: podman/ctlog.yml
  when: ctlog_enabled | bool

- name: Configure/Deploy tuf
  ansible.builtin.include_tasks: podman/tuf.yml
  when: tuf_enabled | bool