---

- name: Set location of Podman Play Manifest
  ansible.builtin.set_fact:
    kube_play_file: "{{ kube_manifest_dir + '/' + podman_spec.kube_file_content.metadata.namespace + '_' + podman_spec.kube_file_content.metadata.name + '.yml' }}"

- name: Copy Manifest to Server
  ansible.builtin.copy:
    content: "{{ podman_spec.kube_file_content | to_nice_yaml(indent=2) }}"
    dest: "{{ kube_play_file }}"

- name: Create Secret
  containers.podman.podman_play:
    kube_file: "{{ podman_spec.secret }}"
    state: "{{ podman_spec.state | default('started') }}"
  when: podman_spec.secret is defined

- name: Copy Systemd file to Server
  ansible.builtin.template:
    src: "systemd/systemd-cm.j2"
    dest: "{{ systemd_directory + '/' + podman_spec.systemd_file }}.service"
  when: podman_spec.configmap is defined

- name: Copy Systemd file to Server
  ansible.builtin.template:
    src: "systemd/systemd-nocm.j2"
    dest: "{{ systemd_directory + '/' + podman_spec.systemd_file }}.service"
  when: podman_spec.configmap is not defined

- name: Start Podman Service
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: "{{ podman_spec.systemd_file }}"